project:
  type: website

website:
  title: "Bui Huu Dai"
  favicon: Github_bird.png
  twitter-card: true
  cookie-consent: true
  open-graph: true
  google-analytics:
    tracking-id: G-6JR4N915S6
    anonymize-ip: true
  site-url: https://buidai123.github.io/blog/
  description: "Dai's blog."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/buidai123
      - icon: twitter-x
        href: https://x.com/daibui1234
      - icon: rss
        href: index.xml
  search:
    location: navbar
    type: textbox

  page-footer:
    left:
      - text: "Copyright 2024, Bui Huu Dai"
  repo-url: https://github.com/buidai123/blog
  repo-actions: [edit, source, issue]

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: hover
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

editor: visual
