project:
  type: website

website:
  title: "Bui Huu Dai"
  twitter-card: true
  open-graph: true
  google-analytics: G-6JR4N915S6
  site-url: https://buidai123.github.io/blog/
  description: "Dai's blog."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/buidai123
      - icon: twitter-x
        href: https://x.com/daibui1234
      - icon: rss
        href: index.xml
#
#  page-footer:
#    right: "This blog is built with ❤️ and [Quarto](https://quarto.org/)."
#

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap

editor: visual



