project:
  type: website

website:
  title: "Bui Huu Dai"
  favicon: Github_bird.png
  twitter-card: true
  cookie-consent: true
  open-graph: true
  google-analytics:
    tracking-id: G-6JR4N915S6
    anonymize-ip: true
  site-url: https://buidai123.github.io/blog/
  description: "Dai's blog."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/buidai123
      - icon: twitter-x
        href: https://x.com/daibui1234
      - icon: rss
        href: index.xml
  search:
    location: navbar
    type: textbox

  page-footer:
    left:
      - text: "Copyright 2024, Bui Huu Dai"
  back-to-top-navigation: true
  repo-url: https://github.com/buidai123/blog
  repo-actions: [edit, source, issue]

format:
  html:
    theme:
      light: cosmo
      dark: [darkly, styles-dark.scss]
    code-copy: hover
    code-overflow: scroll

editor: visual
